import {useReducer,useRef,useState} from 'react';
import {createEmptyDraft} from './model/createDraft';
import {cvReducer} from './model/reducer';
import {extractCvFile} from './extraction/extractCvFile';
import {validateForExport} from './model/validation';
import {requestSuggestions} from './suggestions/suggestionClient';
import {buildApprovedViewModel} from './document/buildApprovedViewModel';
import {createCvDocx,cvFilename} from './document/createDocx';
import {downloadBlob} from './document/downloadBlob';
import CvPreview from './components/CvPreview';
import './cv-builda.css';
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const destinations=[['summary','Professional Summary'],['skills','Technical Skills'],['qualifications','Qualifications'],['employment','Work Experience'],['additional','Additional / Certifications']];
export default function CvBuildaPage({initialState,suggestionTransport=requestSuggestions}={}){
 const [state,dispatch]=useReducer(cvReducer,initialState||createEmptyDraft()); const [status,setStatus]=useState(''); const [view,setView]=useState('editor'); const input=useRef();
 async function load(file){if(!file)return;setStatus('Extracting locally…');try{const x=await extractCvFile(file);dispatch({type:'LOAD_EXTRACTION',file:{name:file.name,size:file.size},fragments:x.fragments,warnings:x.warnings});setStatus('Extraction complete. Assign or exclude every source fragment below.')}catch(e){setStatus(e.message)}}
 function reset(){if(globalThis.confirm('Clear this CV and start over?')){dispatch({type:'RESET'});if(input.current)input.current.value='';setStatus('Session cleared.')}}
 const validation=validateForExport(state);
 async function download(){dispatch({type:'GENERATION_STATUS',status:'working'});setStatus('Creating editable Word document…');try{const blob=await createCvDocx(buildApprovedViewModel(state),state.templateId);downloadBlob(blob,cvFilename(state.personal));dispatch({type:'GENERATION_STATUS',status:'complete'});setStatus('Word CV downloaded. Your draft remains available.')}catch{dispatch({type:'GENERATION_STATUS',status:'error',error:'Word generation failed.'});setStatus('Word generation failed. No candidate information was removed.')}}
 return <div className="builda"><header className="builda-header"><a href="/" className="brand"><span className="brand-main">TALENT TREE</span><span className="brand-sub">EST. 2013</span></a><button className="secondary" onClick={reset}>Start Over</button></header><main><p className="eyebrow">Local, factual CV formatting</p><h1>Talent Tree CV Builda</h1><p className="intro">Format candidate information without inventing or silently removing content. Files remain in this browser session.</p>
 <section className="upload" tabIndex="0" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.current?.click()}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();load(e.dataTransfer.files[0])}}><h2>1. Upload CV</h2><label className="file-label">Choose CV<input ref={input} type="file" accept=".docx,.pdf" onChange={e=>load(e.target.files[0])}/></label><p>Choose or drop a DOCX or text-based PDF (maximum 10 MB).</p>{state.file&&<><strong>{state.file.name}</strong><button type="button" onClick={()=>input.current?.click()}>Replace file</button></>}<p role="status" aria-live="polite">{status}</p></section>
 {state.file&&<><div className="mobile-switch" role="group" aria-label="Workspace view"><button aria-pressed={view==='editor'} onClick={()=>setView('editor')}>Editor</button><button aria-pressed={view==='preview'} onClick={()=>setView('preview')}>Preview</button></div><div className={`workspace show-${view}`}><div className="editor"><h2>2. Review information</h2><label>Candidate name<input value={state.personal.name} onChange={e=>dispatch({type:'SET_PERSONAL',field:'name',value:e.target.value})}/></label><label>Contact details<textarea value={state.personal.contact} onChange={e=>dispatch({type:'SET_PERSONAL',field:'contact',value:e.target.value})}/></label><label>Professional Summary<textarea value={state.summary} onChange={e=>dispatch({type:'SET_FIELD',field:'summary',value:e.target.value})}/></label>
 <RecordEditor title="Qualifications" collection="qualifications" records={state.qualifications} dispatch={dispatch} fields={[['year','Year'],['qualification','Qualification'],['institution','Institution'],['detail','Supplied detail']]}/><RecordEditor title="Certifications" collection="certifications" records={state.certifications} dispatch={dispatch} fields={[['name','Certification']]}/><RecordEditor title="Technical Skills" collection="skills" records={state.skills} dispatch={dispatch} fields={[['detail','Skill or supplied detail']]}/><ExperienceEditor records={state.experience} dispatch={dispatch}/>
 <SourceCoverage state={state} dispatch={dispatch}/><Additional state={state} dispatch={dispatch} transport={suggestionTransport} setStatus={setStatus}/><fieldset><legend>3. Choose template</legend>{['standard','executive'].map(x=><label key={x}><input type="radio" name="template" checked={state.templateId===x} onChange={()=>dispatch({type:'SELECT_TEMPLATE',templateId:x})}/>{x==='standard'?'Standard Talent Tree':'Executive Talent Tree'}</label>)}</fieldset>{!validation.valid&&<div className="warning" role="alert"><strong>Export is blocked</strong><ul>{validation.errors.map(x=><li key={x}>{x}</li>)}</ul></div>}<button onClick={download} disabled={!validation.valid||state.generation.status==='working'}>{state.generation.status==='working'?'Creating Word CV…':'Download editable Word CV'}</button></div><CvPreview state={state}/></div></>}</main></div>;
}
function RecordEditor({title,collection,records,dispatch,fields}){return <section><h3>{title}</h3>{records.map((record,index)=><fieldset className="record" key={record.id||index}><legend>{title} {index+1}</legend>{fields.map(([field,label])=><label key={field}>{label}<input value={record[field]||''} onChange={e=>dispatch({type:'UPDATE_RECORD',collection,id:record.id,changes:{[field]:e.target.value}})}/></label>)}<div className="actions"><button disabled={!index} onClick={()=>dispatch({type:'REORDER_RECORD',collection,id:record.id,index:index-1})}>Move up</button><button disabled={index===records.length-1} onClick={()=>dispatch({type:'REORDER_RECORD',collection,id:record.id,index:index+1})}>Move down</button><button onClick={()=>dispatch({type:'REMOVE_RECORD',collection,id:record.id})}>Remove</button></div></fieldset>)}<button onClick={()=>dispatch({type:'ADD_RECORD',collection,record:{id:id(),...Object.fromEntries(fields.map(([f])=>[f,''])),provenance:'staff'}})}>Add {title.toLowerCase()}</button></section>}
function ExperienceEditor({records,dispatch}){return <section><h3>Work Experience</h3>{records.map((r,index)=><fieldset className="record" key={r.id||index}><legend>Work experience {index+1}</legend>{[['employer','Employer'],['duration','Duration'],['title','Title'],['reason','Reason for leaving']].map(([field,label])=><label key={field}>{label}<input value={r[field]||''} onChange={e=>dispatch({type:'UPDATE_RECORD',collection:'experience',id:r.id,changes:{[field]:e.target.value}})}/></label>)}<label>Responsibilities<textarea value={(r.responsibilities||[]).join('\n')} onChange={e=>dispatch({type:'UPDATE_RECORD',collection:'experience',id:r.id,changes:{responsibilities:e.target.value.split('\n').filter(Boolean)}})}/></label><div className="actions"><button disabled={!index} onClick={()=>dispatch({type:'REORDER_RECORD',collection:'experience',id:r.id,index:index-1})}>Move up</button><button disabled={index===records.length-1} onClick={()=>dispatch({type:'REORDER_RECORD',collection:'experience',id:r.id,index:index+1})}>Move down</button><button onClick={()=>dispatch({type:'REMOVE_RECORD',collection:'experience',id:r.id})}>Remove</button></div></fieldset>)}<button onClick={()=>dispatch({type:'ADD_RECORD',collection:'experience',record:{id:id(),employer:'',duration:'',title:'',reason:'',responsibilities:[],provenance:'staff'}})}>Add work experience</button></section>}
function SourceCoverage({state,dispatch}){const [choices,setChoices]=useState({});return <section><h3>Source Coverage</h3><p>Assign or explicitly exclude every original fragment.</p>{state.fragments.map(f=><article className="fragment" key={f.id}><q>{f.originalText}</q><small>{f.location.page?`Page ${f.location.page}`:`Item ${f.location.order}`}</small><strong>{f.coverage}</strong>{f.coverage==='unreviewed'?<><label>Destination<select value={choices[f.id]||'additional'} onChange={e=>setChoices({...choices,[f.id]:e.target.value})}>{destinations.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button onClick={()=>dispatch({type:'ASSIGN_FRAGMENT',id:f.id,destination:choices[f.id]||'additional'})}>Assign source</button><button onClick={()=>globalThis.confirm('Exclude this source information?')&&dispatch({type:'EXCLUDE_FRAGMENT',id:f.id})}>Exclude source</button></>:<button onClick={()=>dispatch({type:'RESTORE_FRAGMENT',id:f.id})}>Review again</button>}</article>)}</section>}
function Additional({state,dispatch,transport,setStatus}){const [text,setText]=useState('');const pending=state.notes.filter(n=>n.status==='pending');function add(){const notes=text.split(/\n\s*\n|\n(?=[•*-])/).map((x,i)=>({id:`note-${id()}-${i}`,text:x.replace(/^[•*-]\s*/,''),status:'pending'})).filter(x=>x.text.trim());dispatch({type:'ADD_NOTES',notes});setText('')}async function suggest(){setStatus('Requesting optional placement suggestions…');try{const response=await transport({task:'classify_notes',fragments:pending.slice(0,8).map(n=>({id:n.id,text:n.text}))});dispatch({type:'RECEIVE_SUGGESTIONS',suggestions:response.suggestions.map(s=>({...s,originalText:state.notes.find(n=>n.id===s.fragmentId)?.text||''}))});setStatus('Suggestions received. Nothing has been applied.')}catch(e){setStatus(e.message||'Suggestions are unavailable. Continue editing manually.')}}return <section><h3>Additional Candidate Information</h3><label>Paste additional notes<textarea value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={!text.trim()} onClick={add}>Add notes for review</button>{pending.length>0&&<button onClick={suggest}>Suggest destinations</button>}{state.notes.map(n=><article className="record" key={n.id}><p>{n.text}</p><small>Status: {n.status}</small>{n.status==='pending'&&<><button onClick={()=>dispatch({type:'DECIDE_NOTE',id:n.id,decision:{status:'approved',destination:'additional'}})}>Place manually</button><button onClick={()=>dispatch({type:'DECIDE_NOTE',id:n.id,decision:{status:'rejected'}})}>Reject</button></>}</article>)}<SuggestionQueue suggestions={state.suggestions} dispatch={dispatch}/></section>}
function SuggestionQueue({suggestions,dispatch}){if(!suggestions.length)return null;return <section><h4>Suggestion Queue</h4><p>Suggestions never change the CV until you approve them.</p>{suggestions.map(s=><article className="record" key={s.id}><div className="comparison"><div><strong>Original</strong><p>{s.originalText}</p></div><div><strong>Suggested wording</strong><textarea aria-label={`Suggested wording for ${s.fragmentId}`} value={s.proposedText||s.originalText} disabled={s.status!=='pending'} onChange={e=>dispatch({type:'UPDATE_SUGGESTION',id:s.id,changes:{proposedText:e.target.value}})}/></div></div><label>Destination<select disabled={s.status!=='pending'} value={s.destination||'additional'} onChange={e=>dispatch({type:'UPDATE_SUGGESTION',id:s.id,changes:{destination:e.target.value}})}>{destinations.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><p>{s.reason} Confidence: {s.confidence}.</p>{s.warnings?.map(w=><p className="warning" key={w}>{w}</p>)}{s.status==='pending'?<><button onClick={()=>dispatch({type:'DECIDE_SUGGESTION',id:s.id,decision:{status:'approved',destination:s.destination||'additional'}})}>Approve suggestion</button><button onClick={()=>dispatch({type:'DECIDE_SUGGESTION',id:s.id,decision:{status:'rejected'}})}>Reject suggestion</button></>:<strong>Status: {s.status}</strong>}</article>)}</section>}
